services:
  app:
    build: ./
    ports: ["3000:3000"]
    env_file: [./.env]
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install --include=dev && npm run dev"
    depends_on: [mongo]
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
volumes:
  mongo_data:
