services:
  app:
    build:
      context: .
      target: prod
    ports: ["80:3000"]
    env_file: [./.env]
    environment:
      - NODE_ENV=production
    depends_on: [mongo]
    # 不掛載程式碼與 node_modules，使用映像內建置結果

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes: [mongo_data:/data/db]

volumes:
  mongo_data:

